config/routes.rb
CdoApp::Application.routes.draw do

  resources :registro_bovinos

  resources :razas

  resources :users

  resource :admins do
    collection do      
      get 'index'
      get 'data'      
    end
  end

  root :to => 'registro_bovinos#index'

  

end

app/models/raza.rb
class Raza < ActiveRecord::Base
  attr_accessible :codigo, :id, :nombre
end

app/models/registro_bovino.rb
class RegistroBovino < ActiveRecord::Base
  attr_accessible :alta_explotacion, :baja_explotacion, :balance_fecha, :balance_numero_cabezas, :causa_alta, :causa_baja, :comprador_codigo, :comprador_nif, :comprador_nombre, :crotal, :crotal_madre, :id, :nacimiento, :raza, :sexo, :traslado_numero, :traslado_serie, :vendedor_codigo, :vendedor_explotacion, :vendedor_nif, :vendedor_nombre
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :id, :name, :pw, :role
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    def index        
    end
    def data
      @registro_bovinos = RegistroBovino.all
    end    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/razas_controller.rb
class RazasController < ApplicationController
  # GET /razas
  # GET /razas.json
  def index
    @razas = Raza.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @razas }
    end
  end

  # GET /razas/1
  # GET /razas/1.json
  def show
    @raza = Raza.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @raza }
    end
  end

  # GET /razas/new
  # GET /razas/new.json
  def new
    @raza = Raza.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @raza }
    end
  end

  # GET /razas/1/edit
  def edit
    @raza = Raza.find(params[:id])
  end

  # POST /razas
  # POST /razas.json
  def create
    @raza = Raza.new(params[:raza])

    respond_to do |format|
      if @raza.save
        #format.html { redirect_to @raza, notice: 'Raza was successfully created.' }
        format.html { redirect_to action: "index" }
        format.json { render json: @raza, status: :created, location: @raza }        
      else
        format.html { render action: "new" }
        format.json { render json: @raza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /razas/1
  # PUT /razas/1.json
  def update
    @raza = Raza.find(params[:id])

    respond_to do |format|
      if @raza.update_attributes(params[:raza])
        #format.html { redirect_to @raza, notice: 'Raza was successfully updated.' }
        format.html { redirect_to action: "index" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @raza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /razas/1
  # DELETE /razas/1.json
  def destroy
    @raza = Raza.find(params[:id])
    @raza.destroy

    respond_to do |format|
      format.html { redirect_to razas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/registro_bovinos_controller.rb
class RegistroBovinosController < ApplicationController
  # GET /registro_bovinos
  # GET /registro_bovinos.json
  def index
    @registro_bovinos = RegistroBovino.all(:order => "id desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @registro_bovinos }
    end
  end

  # GET /registro_bovinos/1
  # GET /registro_bovinos/1.json
  def show
    @registro_bovino = RegistroBovino.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @registro_bovino }
    end
  end

  # GET /registro_bovinos/new
  # GET /registro_bovinos/new.json
  def new
    @registro_bovino = RegistroBovino.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @registro_bovino }
    end
  end

  # GET /registro_bovinos/1/edit
  def edit
    @registro_bovino = RegistroBovino.find(params[:id])
  end

  # POST /registro_bovinos
  # POST /registro_bovinos.json
  def create
    @registro_bovino = RegistroBovino.new(params[:registro_bovino])

    respond_to do |format|
      if @registro_bovino.save
        #format.html { redirect_to @registro_bovino, notice: 'Registro bovino was successfully created.' }
        format.html { redirect_to action: "index" }
        format.json { render json: @registro_bovino, status: :created, location: @registro_bovino }
      else
        format.html { render action: "new" }
        format.json { render json: @registro_bovino.errors, status: :unprocessable_entity }
      end  
    end
  end

  # PUT /registro_bovinos/1
  # PUT /registro_bovinos/1.json
  def update
    @registro_bovino = RegistroBovino.find(params[:id])

    respond_to do |format|
      if @registro_bovino.update_attributes(params[:registro_bovino])
        #format.html { redirect_to @registro_bovino, notice: 'Registro bovino was successfully updated.' }
        format.html { redirect_to action: "index" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @registro_bovino.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registro_bovinos/1
  # DELETE /registro_bovinos/1.json
  def destroy
    @registro_bovino = RegistroBovino.find(params[:id])
    @registro_bovino.destroy

    respond_to do |format|
      format.html { redirect_to registro_bovinos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/razas_helper.rb
module RazasHelper
end

app/helpers/registro_bovinos_helper.rb
module RegistroBovinosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/index.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <script src="/javascripts/codebase/dhtmlxcommon.js" type="text/javascript" charset="utf-8"></script>
        <script src="/javascripts/codebase/dhtmlxgrid.js" type="text/javascript" charset="utf-8"></script>
        <script src="/javascripts/codebase/dhtmlxgridcell.js" type="text/javascript" charset="utf-8"></script>
        <script src="/javascripts/codebase/ext/dhtmlxgrid_filter.js" type="text/javascript" charset="utf-8"></script>
        <link rel="stylesheet" href="/javascripts/codebase/dhtmlxgrid.css" type="text/css" media="screen" charset="utf-8">
        <link rel="stylesheet" href="/javascripts/codebase/skins/dhtmlxgrid_dhx_skyblue.css" type="text/css" media="screen" charset="utf-8">
    </head>
    <body>
        <%= link_to 'Volver', registro_bovinos_path %>
        <div id="grid_here" style="width:850px; height:600px;">
        </div>
        <script type="text/javascript" charset="utf-8">
            var grid = new dhtmlXGridObject("grid_here");
            grid.setImagePath("/javascripts/codebase/imgs/");
            grid.setHeader("Crotal, Nacimiento, Sexo, Raza, Alta explotacion, Causa alta, Vendedor nombre, Vendedor nif, Vendedor codigo, Vendedor explotacion");
            grid.attachHeader("#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter");
            grid.setColSorting("str,str,str,str,str,str,str,str,str,str");
            grid.setInitWidths("120,80,50,50,80,50,120,80,80,120");
            grid.setSkin("dhx_skyblue");
            grid.init();
            grid.load("/admins/data.xml");
        </script>
        <!--
        <input type="button" value="Add" onclick="grid.addRow(grid.uid(),'new user')">
        <input type="button" value="Delete" onclick="grid.deleteSelectedRows()">
        -->
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CdoApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/razas/_form.html.erb
<%= form_for(@raza) do |f| %>
  <% if @raza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@raza.errors.count, "error") %> prohibited this raza from being saved:</h2>

      <ul>
      <% @raza.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/razas/edit.html.erb
<h1>Editing raza</h1>

<%= render 'form' %>

<%= link_to 'Show', @raza %> |
<%= link_to 'Back', razas_path %>

app/views/razas/index.html.erb
<h1>Listing razas</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Nombre</th>
    <th>Codigo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @razas.each do |raza| %>
  <tr>
    <td><%= raza.id %></td>
    <td><%= raza.nombre %></td>
    <td><%= raza.codigo %></td>
    <td><%= link_to 'Show', raza %></td>
    <td><%= link_to 'Edit', edit_raza_path(raza) %></td>
    <td><%= link_to 'Destroy', raza, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Raza', new_raza_path %>

app/views/razas/new.html.erb
<h1>New raza</h1>

<%= render 'form' %>

<%= link_to 'Back', razas_path %>

app/views/razas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @raza.id %>
</p>

<p>
  <b>Nombre:</b>
  <%= @raza.nombre %>
</p>

<p>
  <b>Codigo:</b>
  <%= @raza.codigo %>
</p>


<%= link_to 'Edit', edit_raza_path(@raza) %> |
<%= link_to 'Back', razas_path %>

app/views/registro_bovinos/_form.html.erb
<link rel="stylesheet" type="text/css" href="/javascripts/codebase/dhtmlxcalendar.css"/>
<link rel="stylesheet" type="text/css" href="/javascripts/codebase/skins/dhtmlxcalendar_dhx_skyblue.css"/>
<script src="/javascripts/codebase/dhtmlxcalendar.js"></script>
<script>
  dhtmlXCalendarObject.prototype.langData["es"] = {
      //dateformat: '%d.%m.%Y',
      monthesFNames: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
      monthesSNames: ["Ene", "Feb", "Mar", "Abr", "Мay", "Jun", "Jul", "Аgo", "Sep", "Oct", "Nov", "Dic"],
      daysFNames: ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
      daysSNames: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"],
      weekstart: 1
  } 
  function doOnLoad() {
      
      var myCalendar;      
      myCalendar = new dhtmlXCalendarObject(["registro_bovino_nacimiento","registro_bovino_alta_explotacion","registro_bovino_baja_explotacion"/*,"registro_bovino_balance_fecha"*/]);
      myCalendar.loadUserLanguage('es');
  }
</script>

<%= form_for(@registro_bovino) do |f| %>
  <% if @registro_bovino.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registro_bovino.errors.count, "error") %> prohibited this registro_bovino from being saved:</h2>

      <ul>
      <% @registro_bovino.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit :onmousedown => 'this.title=1', :onclick => 'if(this.title!=1){return false;}' %>
  </div>

  <div class="field">
    <!--<%= f.label :id %><br />
    <%= f.number_field :id %> -->
    <%= f.hidden_field :id %>    
  </div>
  <div class="field">
    <%= f.label :crotal %><br />
    <%= f.text_field :crotal %>
  </div>
  <div class="field">
    <%= f.label :nacimiento %><br />
    <%= f.text_field :nacimiento %>    
    <!--<%= f.date_select :nacimiento %>-->    
  </div>
  <div class="field">
    <%= f.label :sexo %><br />
    <!-- <%= f.text_field :sexo %> -->    
    <%= f.radio_button :sexo, 'M' , {:checked => true}%> 
    <%= f.label :sexo, 'M', :value => 'M' %>
    <%= f.radio_button :sexo, 'H' %>
    <%= f.label :sexo, 'H', :value => 'H' %>
  </div>
  <div class="field">
    <%= f.label :raza %><br />
    <!--<%= f.text_field :raza %>-->
    <%= f.collection_select :raza, Raza.find(:all, :order => "nombre ASC"), :codigo, :nombre, {:include_blank => true} %>
  </div>
  <div class="field">
    <%= f.label :alta_explotacion %><br />
    <%= f.text_field :alta_explotacion %>
    <!--<%= f.date_select :alta_explotacion %>-->
  </div>
  <div class="field">
    <%= f.label :causa_alta %><br />
    <!--<%= f.text_field :causa_alta %>-->
    <%= f.radio_button :causa_alta, 'C' , {:checked => true}%> 
    <%= f.label :causa_alta, 'Compra', :value => 'C' %>
    <%= f.radio_button :causa_alta, 'N' %>
    <%= f.label :causa_alta, 'Nacimiento', :value => 'N' %>
    <%= f.radio_button :causa_alta, 'R' %>
    <%= f.label :causa_alta, 'Reposicion temporal', :value => 'R' %>    
  </div>
  <div class="field">
    <%= f.label :vendedor_nombre %><br />
    <%= f.text_field :vendedor_nombre %>
  </div>
  <div class="field">
    <%= f.label :vendedor_nif %><br />
    <%= f.text_field :vendedor_nif %>
  </div>
  <div class="field">
    <%= f.label :vendedor_codigo %><br />
    <%= f.text_field :vendedor_codigo %>
  </div>
  <div class="field">
    <%= f.label :vendedor_explotacion %><br />
    <%= f.text_field :vendedor_explotacion %>
  </div>
  <div class="field">
    <%= f.label :crotal_madre %><br />
    <%= f.text_field :crotal_madre %>
  </div>
  <div class="field">
    <%= f.label :baja_explotacion %><br />
    <%= f.text_field :baja_explotacion %>
    <!--<%= f.date_select :baja_explotacion, :include_blank => true %>-->
  </div>
  <div class="field">
    <%= f.label :causa_baja %><br />
    <!--<%= f.text_field :causa_baja %>-->
    <%= f.radio_button :causa_baja, 'S' %> 
    <%= f.label :causa_baja, 'Venta para sacrificio', :value => 'S' %>
    <%= f.radio_button :causa_baja, 'V' %>
    <%= f.label :causa_baja, 'Venta para vida', :value => 'V' %>
    <%= f.radio_button :causa_baja, 'T' %>
    <%= f.label :causa_baja, 'Baja temporal', :value => 'T' %>    
  </div>
  <div class="field">
    <%= f.label :comprador_nombre %><br />
    <%= f.text_field :comprador_nombre %>
  </div>
  <div class="field">
    <%= f.label :comprador_nif %><br />
    <%= f.text_field :comprador_nif %>
  </div>
  <div class="field">
    <%= f.label :comprador_codigo %><br />
    <%= f.text_field :comprador_codigo %>
  </div>  
  <div class="field">
    <%= f.label :traslado_serie %><br />
    <%= f.text_field :traslado_serie %>
  </div>
  <div class="field">
    <%= f.label :traslado_numero %><br />
    <%= f.text_field :traslado_numero %>
  </div>
  <div class="field">
    <%= f.label :balance_fecha %><br />
    <!--<%= f.text_field :balance_fecha %>-->
    <%= f.date_select :balance_fecha %>
  </div>
  <div class="field">
    <%= f.label :balance_numero_cabezas %><br />
    <%= f.number_field :balance_numero_cabezas %>
  </div>
  <div class="actions">
    <%= f.submit :onmousedown => 'this.title=1', :onclick => 'if(this.title!=1){return false;}' %>    
  </div>
<% end %>
<script>window.onload = doOnLoad;</script>
<!-- <input type="submit" name="mybutton" onmousedown="this.title=1" onclick="if(this.title!=1){return false;}" value="Submit my Form" /> -->

app/views/registro_bovinos/edit.html.erb
<h1>Edición de un animal</h1>

<%= link_to 'Ver', @registro_bovino %> |
<%= link_to 'Volver', registro_bovinos_path %>

<%= render 'form' %>

<%= link_to 'Ver', @registro_bovino %> |
<%= link_to 'Volver', registro_bovinos_path %>

app/views/registro_bovinos/index.html.erb
<h1>Registro de animales</h1>
 
<%= link_to 'Búsquedas', admins_path %> | <%= link_to 'Añadir animal', new_registro_bovino_path %>

<table>
  <tr>
    <th></th>
    <th></th>
    <th>Id</th>
    <th>Crotal</th>
    <th>Nacimiento</th>
    <th>Sexo</th>
    <th>Raza</th>
    <th>Alta explotacion</th>
    <th>Causa alta</th>
    <th>Vendedor nombre</th>
    <th>Vendedor nif</th>
    <th>Vendedor codigo</th>
    <th>Vendedor explotacion</th>
    <th>Crotal madre</th>    
    <th>Baja explotacion</th>
    <th>Causa baja</th>
    <th>Comprador nombre</th>
    <th>Comprador nif</th>
    <th>Comprador codigo</th>    
    <th>Traslado serie</th>
    <th>Traslado numero</th>
    <th>Balance fecha</th>
    <th>Balance numero cabezas</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @registro_bovinos.each do |registro_bovino| %>
  <tr>
    <td><%= link_to 'Ver', registro_bovino %></td>
    <td><%= link_to 'Editar', edit_registro_bovino_path(registro_bovino) %></td>
    <td><%= registro_bovino.id %></td>
    <td><%= registro_bovino.crotal %></td>
    <td><%= registro_bovino.nacimiento %></td>
    <td><%= registro_bovino.sexo %></td>
    <td><%= registro_bovino.raza %></td>
    <td><%= registro_bovino.alta_explotacion %></td>
    <td><%= registro_bovino.causa_alta %></td>
    <td><%= registro_bovino.vendedor_nombre %></td>
    <td><%= registro_bovino.vendedor_nif %></td>
    <td><%= registro_bovino.vendedor_codigo %></td>
    <td><%= registro_bovino.vendedor_explotacion %></td>
    <td><%= registro_bovino.crotal_madre %></td>    
    <td><%= registro_bovino.baja_explotacion %></td>
    <td><%= registro_bovino.causa_baja %></td>
    <td><%= registro_bovino.comprador_nombre %></td>
    <td><%= registro_bovino.comprador_nif %></td>
    <td><%= registro_bovino.comprador_codigo %></td>    
    <td><%= registro_bovino.traslado_serie %></td>
    <td><%= registro_bovino.traslado_numero %></td>
    <td><%= registro_bovino.balance_fecha %></td>
    <td><%= registro_bovino.balance_numero_cabezas %></td>
    <td><%= link_to 'Ver', registro_bovino %></td>
    <td><%= link_to 'Editar', edit_registro_bovino_path(registro_bovino) %></td>
    <td><%= link_to 'Borrar', registro_bovino, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Añadir animal', new_registro_bovino_path %>

app/views/registro_bovinos/new.html.erb
<h1>Añadiendo animal</h1>

<%= link_to 'Volver', registro_bovinos_path %>

<%= render 'form' %>

<%= link_to 'Volver', registro_bovinos_path %>

app/views/registro_bovinos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Editar', edit_registro_bovino_path(@registro_bovino) %> |
<%= link_to 'Volver', registro_bovinos_path %>

<p>
  <b>Id:</b>
  <%= @registro_bovino.id %>
</p>

<p>
  <b>Crotal:</b>
  <%= @registro_bovino.crotal %>
</p>

<p>
  <b>Nacimiento:</b>
  <%= @registro_bovino.nacimiento %>
</p>

<p>
  <b>Sexo:</b>
  <%= @registro_bovino.sexo %>
</p>

<p>
  <b>Raza:</b>
  <%= @registro_bovino.raza %>
</p>

<p>
  <b>Causa alta:</b>
  <%= @registro_bovino.causa_alta %>
</p>

<p>
  <b>Vendedor nombre:</b>
  <%= @registro_bovino.vendedor_nombre %>
</p>

<p>
  <b>Vendedor nif:</b>
  <%= @registro_bovino.vendedor_nif %>
</p>

<p>
  <b>Vendedor codigo:</b>
  <%= @registro_bovino.vendedor_codigo %>
</p>

<p>
  <b>Vendedor explotacion:</b>
  <%= @registro_bovino.vendedor_explotacion %>
</p>

<p>
  <b>Crotal madre:</b>
  <%= @registro_bovino.crotal_madre %>
</p>

<p>
  <b>Alta explotacion:</b>
  <%= @registro_bovino.alta_explotacion %>
</p>

<p>
  <b>Causa baja:</b>
  <%= @registro_bovino.causa_baja %>
</p>

<p>
  <b>Comprador nombre:</b>
  <%= @registro_bovino.comprador_nombre %>
</p>

<p>
  <b>Comprador nif:</b>
  <%= @registro_bovino.comprador_nif %>
</p>

<p>
  <b>Comprador codigo:</b>
  <%= @registro_bovino.comprador_codigo %>
</p>

<p>
  <b>Baja explotacion:</b>
  <%= @registro_bovino.baja_explotacion %>
</p>

<p>
  <b>Traslado serie:</b>
  <%= @registro_bovino.traslado_serie %>
</p>

<p>
  <b>Traslado numero:</b>
  <%= @registro_bovino.traslado_numero %>
</p>

<p>
  <b>Balance fecha:</b>
  <%= @registro_bovino.balance_fecha %>
</p>

<p>
  <b>Balance numero cabezas:</b>
  <%= @registro_bovino.balance_numero_cabezas %>
</p>


<%= link_to 'Editar', edit_registro_bovino_path(@registro_bovino) %> |
<%= link_to 'Volver', registro_bovinos_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :role %><br />
    <%= f.number_field :role %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :pw %><br />
    <%= f.text_field :pw %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Role</th>
    <th>Email</th>
    <th>Pw</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.role %></td>
    <td><%= user.email %></td>
    <td><%= user.pw %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @user.id %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Role:</b>
  <%= @user.role %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Pw:</b>
  <%= @user.pw %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>